---
title: "Survey data analysis for FORCE2021 Presentation"
author: "Stephanie J. Spielman"
output: 
  html_document:
    theme: simplex
    highlight: tango
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, include=TRUE,warning = FALSE, message=FALSE, fig.height = 4, fig.width = 6)
library(tidyverse)
library(readxl)
library(patchwork)
library(RColorBrewer)
theme_set(theme_minimal() + 
            theme(plot.title = element_text(size = rel(1.5)),
                  plot.title.position = "plot",
                  axis.text = element_text(size = rel(1.2)),
                  axis.title = element_text(size = rel(1.2)),
                  strip.text = element_text(size = rel(1.2)),
                  legend.position = "bottom")
)

```
<br><br>

<!--
##### Notes on data cleaning (for Stephanie)

+ The headers ending in `_TEXT` provide the survey responses for the associated questions' "Other" field.
+ Questions with `_` but without `_TEXT` are for multiple choice grids

-->

<!--
### Data reading and cleaning 
-->
```{r clean}

# Read in the raw data and define some settings for representing NA answers in plots
raw <- readxl::read_xlsx("raw_survey_results_11-8-21.xlsx")
na_string <- "No answer"
na_color <- "grey80"
bar_outline_color <- "gray40"


# Create a dataset with demographics data only
raw %>% 
  select(ResponseId, starts_with("Q")) %>%
  select(-Q1, -Q_RecaptchaScore) %>%
  slice(-1, -2) %>%
  rename(gender = Q2,
         age_range = Q3,
         institution_type = Q4,
         primary_role = Q5,
         primary_appointment = Q6) %>%
  select(-starts_with("Q")) %>%
  replace_na(list(gender = na_string, 
                  age_range  = na_string, 
                  institution_type = na_string,
                  primary_role = na_string, 
                  primary_appointment = na_string)) -> demographics_data
         

# Create dataset just containing the survey questions for reference
raw %>% 
  slice(1) %>%
  select(starts_with("Q")) %>%
  select(-Q1, -Q_RecaptchaScore) %>% # Q1 is just agreeing to be >=18 years old.
  pivot_longer(everything(), 
               names_to = "header", 
               values_to = "question") -> survey_questions 

# Order for pirate websites to appear in plots
pirate_order <- c("Sci-Hub", "Library Genesis", "ZLibrary", "Aaaaarg")

           
# Data creation: have you heard of the websites and do you use them?
raw %>% 
  select(ResponseId, starts_with("Q11"), starts_with("Q12")) %>%
  slice(-1, -2) %>%
  pivot_longer(starts_with("Q"), 
               names_to = "pirate", 
               values_to= "survey_answer") %>%
  mutate(question = ifelse(str_starts(pirate, "Q11"),
                           "heardof", 
                           "use")) %>%
  mutate(pirate = case_when(
    str_ends(pirate, "_1") ~ pirate_order[1],
    str_ends(pirate, "_2") ~ pirate_order[2],
    str_ends(pirate, "_3") ~ pirate_order[3],
    str_ends(pirate, "_4") ~ pirate_order[4],
  )) %>%
  replace_na(list(survey_answer = na_string)) -> heardof_use_pirate
```


## Demographics and institutional affiliations
<br>


```{r gender_age, fig.width = 12}
gender_colors <- c(na_color, brewer.pal(5, "Set1"))
demographics_data %>%
  group_by(gender) %>%
  count(gender) %>%
  ungroup() %>%
  mutate(gender = fct_reorder(gender, n),
         gender = fct_relevel(gender, na_string)) %>%
  ggplot() + 
  aes(y = gender, x = n, fill = gender) + 
  geom_col(color =  "gray40", alpha = 0.8) + 
  geom_text(aes(x = n+4, label = n))+
  scale_fill_manual(values = gender_colors) + 
  labs(x = "Number of respondents", 
       y = "Gender", 
       title = "Genders of survey respondents") + 
  theme(legend.position = "none") +
  xlim(0, 115) -> gender_barplot


age_colors <- c(na_color, brewer.pal(5, "Reds"))
demographics_data %>%
  group_by(age_range) %>%
  count(age_range) %>%
  ungroup() %>%
  mutate(age_range = fct_relevel(age_range, na_string)) %>%
  ggplot() + 
  aes(y = age_range,x= n, fill = age_range) + 
  geom_col(color =  "gray50", alpha = 0.8) + 
  geom_text(aes(x = n+4, label = n))+
  scale_fill_manual(values = age_colors) + 
  labs(x = "Number of respondents", 
       y = "Age ranges", 
       title = "Age ranges of survey respondents") + 
  theme(legend.position = "none") +
  xlim(0, 75) -> age_barplot

gender_barplot + age_barplot
```

<br>


```{r institution, fig.width = 12}
inst_type_colors <- c(na_color, brewer.pal(3, "Dark2"))
demographics_data %>%
  group_by(institution_type) %>%
  count(institution_type) %>%
  ungroup() %>%
  mutate(institution_type = case_when(
    str_detect(institution_type, "University") ~ "University (R)",
    str_detect(institution_type, "Four-year") ~ "College (UG)",
    str_detect(institution_type, "Junior") ~ "Community/Junior/\nTechnical", 
    TRUE ~ na_string
  )) %>%
  mutate(institution_type = fct_reorder(institution_type, n),
         institution_type = fct_relevel(institution_type, na_string)) %>%
  ggplot() + 
  aes(y = institution_type, x = n, fill = institution_type) + 
  geom_col(color =  "gray40", alpha = 0.9) + 
  geom_text(aes(x = n+6, label = n))+
  scale_fill_manual(values = inst_type_colors) + 
  labs(x = "Number of respondents", 
       title = "Types of institutions", 
       y = "") +
  theme(legend.position = "none") +
  xlim(0, 150)-> inst_type_plot



primary_role_colors <- c(na_color, brewer.pal(3, "Paired"))
demographics_data %>%
  mutate(primary_role = ifelse(str_detect(primary_role, "Professor"), "Professor", primary_role)) %>%
  group_by(primary_role) %>%
  count(primary_role) %>%
  ungroup() %>%
  mutate(primary_role = fct_reorder(primary_role, n),
         primary_role = fct_relevel(primary_role, na_string)) %>%
  ggplot() + 
  aes(y = primary_role, x = n, fill = primary_role) + 
  geom_col(color =  bar_outline_color, alpha = 0.9) + 
  geom_text(aes(x = n+5, label = n))+
  scale_fill_manual(values = primary_role_colors) + 
  labs(x = "Number of respondents", 
       y = "", 
       title = "Primary roles of respondents") +
  theme(legend.position = "none") +
  xlim(0, 110) -> role_plot



inst_type_plot + role_plot

```


```{r affil, fig.width = 8}
# Some people have MULTIPLE affiliations so this is not per person. 
demographics_data %>%
  mutate(clean_affil = str_replace_all(primary_appointment, 
                                       "\\s*\\([,\\s\\w]+\\)\\s*",
                                       "")) %>%
  select(clean_affil) %>%
  separate_rows(clean_affil, sep = ",") %>%
  mutate(clean_affil = ifelse(clean_affil == "Other" | clean_affil == na_string, 
                              "Other/no answer", 
                              clean_affil)
        ) %>%
  count(clean_affil) %>%
  mutate(clean_affil = fct_reorder(clean_affil, n),
         clean_affil = fct_relevel(clean_affil, "Other/no answer")) %>%
  ggplot() + 
  aes(y = clean_affil, 
      x = n, fill = clean_affil) + 
  geom_col(color = bar_outline_color, alpha = 0.9) +
  geom_text(aes(label = n, x = n+2)) + 
  scale_fill_manual(values = c(na_color, rep("darkslateblue", 7))) +
 # scale_fill_brewer(palette = "Dark2") +
  labs(title = "Primary affiliations of respondents", x = "", y = "") +
  theme(legend.position = "none")
```



## Have you heard of and/or use pirate sites?

<br><br>

 
```{r haveyouheard, fig.width = 10, fig.height = 5}

heardof_use_pirate %>%
  filter(question == "heardof") %>%
  left_join(
    demographics_data %>%
      select(ResponseId, primary_role) %>%
      filter(primary_role == "Librarian" | str_detect(primary_role, "Professor"))
  ) %>%
  mutate(survey_answer = fct_relevel(survey_answer, "Yes", "No", na_string),
         pirate = fct_relevel(pirate, pirate_order)) %>%
  count(pirate, survey_answer, primary_role) %>%
  drop_na() %>%
  ggplot() + 
  aes(y = pirate, x = n, fill = survey_answer) + 
  geom_col(position = position_dodge(width = 0.9), color = "black") +
  facet_wrap(vars(primary_role)) +
  geom_text(position = position_dodge(width = 0.9), aes(label = n, x = n+2.5), size = 4) + 
  scale_fill_viridis_d(alpha = 0.8) +
  labs(y = "Pirate website", 
       x = "Number of respondents",
       fill = "Survey response", 
       title = "Have you heard of this resource?")
```

<br>

The plot below **only considers** individuals who have heard of the resource. Responses "Always", "Most of the time", "About half the time", "Sometimes" were grouped together as *"Yes. to some degree"* for quick presentation. 

```{r ifheard_doyouuse, fig.width = 10, fig.height = 5}
# Considering only when heardof!!

heardof_use_pirate %>%
  filter(question == "heardof",
         survey_answer == "Yes") %>%
  select(-question, -survey_answer) %>%
  inner_join(heardof_use_pirate) %>%
    left_join(
    demographics_data %>%
      select(ResponseId, primary_role) %>%
      filter(primary_role == "Librarian" | str_detect(primary_role, "Professor"))
  ) %>%
  # 0 rows, good.
  #filter(question == "heardof", survey_answer != "Yes")
  filter(question == "use") %>%
  mutate(survey_answer = ifelse(survey_answer != "Never", "Yes, to some degree", "Never"),
         survey_answer = fct_relevel(survey_answer, "Yes, to some degree"),
         #fct_relevel(survey_answer, c("Always", "Most of the time", "About half the time", "Sometimes", "Never")),
         pirate = fct_relevel(pirate, pirate_order)) %>%
  count(pirate, survey_answer, primary_role) %>%
  drop_na() %>%
  ggplot() + 
  aes(y = pirate, x = n, fill = survey_answer) + 
  geom_col(position = position_dodge(width = 0.9), color = "black") +
  geom_text(position = position_dodge(width = 0.9), aes(label = n, x = n+2), size = 4) + 
  scale_fill_viridis_d(alpha = 0.8) +
  facet_wrap(vars(primary_role)) +
  labs(y = "Pirate website", 
       x = "Number of respondents",
       fill = "Survey response", 
       title = "For those who have heard of the resource, do you use it at all?")
 


```